### ISSUE TITLE
Playing courses

### ISSUE THREAD

**Issue by Chakratos** [ca25nada/spawncamping-wallhack#11]
Hey,
i wanted to ask how hard it would be to implement the feature to play courses.
I just can't find any theme that has an NPS Display and can play courses.
Since i use this skin for a long time now, if it would be in my skill range i would like to add this to your Theme, i just need to know why it isn't supported yet so i know what i need to do.

**Comment by ca25nada** [comment]
I'm lazy. Most of the theme was written assuming the regular playmode since only a small minority of people plays other modes.

I started rewriting some portions of the theme to support nonstop/course modes a while ago but don't expect it anytime soon.

**Comment by ca25nada** [comment]
Since the theme is moving over to be used on Etterna instead, don't think this will happen now.
