### ISSUE TITLE
Invalid preview mode: 5

### ISSUE THREAD

**Issue by ghost** [ca25nada/spawncamping-wallhack#12]
I am trying to use this theme with Stepmania 5.0.12 on a Mac, but when I open it, it comes up with this screen. If I then press enter, Stepmania crashes and creates this error log.
<img width="871" alt="screen shot 2017-07-31 at 22 34 44" src="https://user-images.githubusercontent.com/13819686/28789919-a309b382-7640-11e7-9248-c8a60c377143.png">
[crashinfo.txt](https://github.com/ca25nada/spawncamping-wallhack/files/1188357/crashinfo.txt)

**Comment by ca25nada** [comment]
Download the version for [SM5 not SM 5.1](https://github.com/ca25nada/spawncamping-wallhack/releases/tag/2.0.2_SM5)
