### ISSUE TITLE
Hello I'm new

### ISSUE THREAD

**Issue by Kuroneko-Gamer** [ca25nada/spawncamping-wallhack#13]
Hi I'm new to using theme in Stepmania 5...my version right now is 5.0.12.
I applied the theme but it looks odd...
![stepmania_2017-10-09_22-37-07](https://user-images.githubusercontent.com/13788856/31332316-6e781800-ad42-11e7-982a-115fe1a34dc5.png)
![stepmania_2017-10-09_22-37-05](https://user-images.githubusercontent.com/13788856/31332318-6e7f9134-ad42-11e7-911a-63f799bedd4f.png)
![stepmania_2017-10-09_22-36-53](https://user-images.githubusercontent.com/13788856/31332321-6ebd6d10-ad42-11e7-97a5-2e549e0e6bd1.png)
![stepmania_2017-10-09_22-36-47](https://user-images.githubusercontent.com/13788856/31332317-6e7f4fd0-ad42-11e7-9915-1e39b30d0fbe.png)

also my score screen is just blank

**Comment by ca25nada** [comment]
Download from [releases](https://github.com/ca25nada/spawncamping-wallhack/releases/tag/2.0.2_SM5) instead of pulling from master
