### ISSUE TITLE
Music preview not playing?

### ISSUE THREAD

**Issue by FinlayDaG33k** [ca25nada/spawncamping-wallhack#15]
I've cloned the git repo and setup the theme, however, the previews of songs do not play in the selection menu.
They do play fine in the default SM5 skin.

**Comment by ca25nada** [comment]
SM version and the Branch you pulled from?
Does the theme throw any errors at all?

**Comment by FinlayDaG33k** [comment]
version 5.0.12 (`20160811 00:34:46`) as it's the latest on stepmania.com
no errors and pulled from the Master branch

**Comment by ca25nada** [comment]
Master branch is unsupported on SM 5.0.12
Download 0.58.x version of Etterna or download from releases for SM5.0.12.
https://github.com/ca25nada/spawncamping-wallhack/releases/tag/2.0.2_SM5

**Comment by FinlayDaG33k** [comment]
Installed it and it seems to work fine now.
