### ISSUE TITLE
Minimal results screen for scoreposting

### ISSUE THREAD

**Issue by foxfire667** [ca25nada/spawncamping-wallhack#24]
One of the most divisive things about SCWH seems to be the results screen. I have heard many a complaint lodged in various elements of it, ranging from the horizontal judgement layout, the overabundance of information (appearing as 'clutter'), or more simply just that it's too small to see. From the prospective of score posting, SCWH is effectively not possible to read unless you full zoom. 

This is where the **minimalist results screen** could play a huge roll in giving some relief to these lobbied issues! 

### Overview
This screen intends to serve for two purposes, these include:
- Ensuring all screenshots are extremely clear and concise for score posting, only containing the most important data a viewer of a score on the outside would care about, and...
- Providing an alternative to SCWH's default screen entirely, if one so chooses, by having it be the default instead of a toggle. 

### Mock-up and layout
![Score screen minimal](https://user-images.githubusercontent.com/7039995/64897483-8dba4280-d651-11e9-9af6-d10bcff1b96d.png)
As you can see, while the style still resembles SCWH, the layout has been altered a fair deal. It aims to ensure relevant information is displayed as clearly and in the order of interest as reasonably possible, while keeping the number of areas for the eyes to wonder to at a minimum.   

The information placed within the screen is as follows (ordered by topmost position): 
- **Pack title** (easiest way to give a sense of location, or denote a file variation)
- **Song title** (hiding this would be mega bad)
- **Rate** (necessary for any speed / control scores, stands out in color because of title changing size)
- **Artist** (can be important if there are multiple songs with the same name in a pack)
- **SSR** (need to know what you earned) 
- **Difficulty** (necessary for files with multiple difficulties)
- **WIFE%** (need to know how well you scored) 
- **Grade** (useful quick reference for score posting)

The above creates what I will call a _quick grade_ assessment. Basically when someone posts a score, you can extremely quickly know X person did Y on Z file. Below is a snippet of the _quick grade_ in action.
![image](https://user-images.githubusercontent.com/7039995/64897747-77f94d00-d652-11e9-8396-e58b45f8036e.png)

- **Judgments** (need to know how the player hit the notes)
- **Judgment percents** (useful quick guide for ratios when viewing speed scores)
- **Holds / Rolls / Mines** (need to know how you dealt with these frequently used objects)
- **Mean** (important info if a player needs to be told they have an issue with offset)
- **Judge** (need to know what timing difficulty the player is using)
- **Offset plot** (useful display info to showcase where user error occurred, and how) 
- **Song Background** (add additional familiarity recognition, also looks nice and takes no space)

There is also a small segment dedicated to the profile information, so screenshots can be posted by people who aren't the player. 

- **Profile avatar** (faster personal identification, helps balance the text)
- **Username** (need to know who posted the score)
- **Overall rating** (quick reference of how high their skill is, to gauge score value) 
- **Date and time** (reference to when a score was set, in the event of posting a past score)
- **Scroll modifier** (necessary to denote CMod vs XMod for specific files)
- **Specific game altering modifiers** (to denote potentially invalidating settings only)

### Feature execution detail
While I believe the majority of this is very straightforward, there are definitely some things which I should explicitly point out to prevent either something breaking or becoming self defeating. In addition, how the minimal score screen will work in tandem with the main screen will also be addressed. 

- There is a 20% opacity color over the BG to prevent it from being too jarring. In this case it'd just be a whole screen quad with the background color so it's configurable. 

- Pack title, song title, and artist title **must be locked to a fixed amount of characters** before cutting off the remainder of the string with an ellipses (...). The text must **absolutely never shrink** in size to accommodate extremely long titles, as this will make them unreadable. 

- Profile name **may shrink**, but should try to **grab from Etterna online** to display username if the player is logged in. Profile rating should also try to grab from Etterna online if it is possible to do so. 

- Relevant mods to showcase under the date would **only be ones which can invalidate a score**, such as NoFail, NoMines/Holds/Jumps/Etc, Shuffle/Cement Mixer, or anything else which falls into the category of a player needing to know something is up with a posted score. Visual mods which **don't alter the chart** or life conditions are **not useful knowledge** in basically any score posted. Noteskin, mini percentage, and overhead/distant preference also fall into the irrelevant category. 

- This score screen is intended to be used as a **supplement to the main screen**, meaning the user should be able to toggle it by pressing a key first, or the screen could automatically change if the user presses the print-screen key. 

- In the event the player wishes to have this be the main screen, and the highly detailed one be the supplement instead, there should be a **player option** giving the player the ability to determine **which score screen shows by default** with results are reached. 

### On a few bits of info I chose to remove
Not covering all of it, but I will go over a few people might actually notice:
- **Song banner** (generally not more useful than the BG and adds clutter, if it isn't literally just a shrunk down variant of the BG like it is most of the time)
- **Life difficulty / life graph** (irrelevant in basically every aspect ever)
- **Left / Right CBs** (rarely relevant, if they are the user generally brings it up themselves)
- **ABS / SD** (ABS is basically never used, even by the player; SD is only mentioned in extremely obscene acc scores [99.995+] and is thus not worth an entry here)
- **Local leader-board** (effectively clutter to someone looking at a score, a user posting should only be posting a score if they think it's their best anyway)

Alright, I believe that covers everything! Let me know if any clarification is necessary, or if something critical appears to be missing from the minimal screen. A reminder again that this is critical information from the viewpoint of a **player looking at a screenshot of a score**, not necessarily the player themselves missing out on some useful info (e.g. local leader-boards, online leader-boards, replays, plot swapping)

**Comment by poco0317** [comment]
handled in 2.2.2 release with some slight changes
