### ISSUE TITLE
Profile Exp only updates once per session

### ISSUE THREAD

**Issue by theminty1** [ca25nada/spawncamping-wallhack#31]
After using the StepMania 5 version of the theme I've decided to take the plunge and test it out on Etterna. While everything else seems completely functional, it seems that the Exp gained doesn't add up at all after each song and only updates on a complete restart.

I'm using Etterna version 0.70.1, if that helps.

**Comment by poco0317** [comment]
fixed with .71 clientside updates and changes that will come when .71 for this theme is released
