### ISSUE TITLE
Inaccurate time bar

### ISSUE THREAD

**Issue by NekoAlosama** [ca25nada/spawncamping-wallhack#33]
Some songs I've played have the time bar finishing before the song actually finishes. This does not happen when using Til' Death.

Example on ['Senbonzakura' (Harbyter)](https://github.com/ca25nada/spawncamping-wallhack/files/6744706/Senbonzakura.Harbyter.zip) on 'osu!mania Ranked to StepMania Pack 1' by NightBunny8:
Til' Death ([Etterna 0.70.3, purposely not using 0.70.4](https://github.com/etternagame/etterna/releases/tag/v0.70.3)):
![Til' Death](https://user-images.githubusercontent.com/47763383/124048982-86f6ee00-d9e5-11eb-9a56-c66c5a566c89.png)

[spawncamping-wallhack 2.2.5](https://github.com/ca25nada/spawncamping-wallhack/releases/tag/2.2.5) (Etterna 0.70.1):
![spawncamping-wallhack](https://user-images.githubusercontent.com/47763383/124048983-878f8480-d9e5-11eb-93b8-b4c1e621fe27.png)

**Comment by poco0317** [comment]
this is fixed for the upcoming release of 0.71 5cee8f5448bcf64bf4fd7f3e3aceba0816df80ae

be on the lookout

**Comment by NekoAlosama** [comment]
Just putting this here so I don't keep forgetting:
https://github.com/poco0317/spawncamping-wallhack/releases/latest
