### ISSUE TITLE
Theme causing crash on OSX when loading profile, stepmania 5.0.11

### ISSUE THREAD

**Issue by mattbox** [ca25nada/spawncamping-wallhack#6]
Game loads up fine, but the main menu colors are all white. All the settings work except "Color Config" which freezes the game. Once I select start, the game crashes load the profile.I got version a9aa593 to work on my computer running 5.0.11 

Included is the crash report from osx
[crashinfo.txt](https://github.com/ca25nada/spawncamping-wallhack/files/211643/crashinfo.txt)

**Comment by ca25nada** [comment]
You're probably pulling from master which isn't supported on 5.0.x versions as of https://github.com/ca25nada/spawncamping-wallhack/commit/7fe08455803373ddf0459daabdfbc0ae48f94adf
Pull from the [5.0](https://github.com/ca25nada/spawncamping-wallhack/tree/5.0) branch instead or download from [release](https://github.com/ca25nada/spawncamping-wallhack/releases/tag/1.0.0)

If you were actually pulling from 5.0 then let me know.

**Comment by mattbox** [comment]
ah, my mistake I was using master, the latest version in the 5.0 branch works perfectly.

Thanks

**Comment by RaymondTracer** [comment]
Can you mention this in the Issues section of the readme.md file or something? I was about to open a new issue, luckily I checked the closed issues first. This issue isn't exclusive to OSX.

**Comment by ca25nada** [comment]
It's already mentioned (albeit kinda vaguely) on the readme of the master branch. I'll make it clearer later.
